### ISSUE TITLE
Unpack requires a buffer of 275 bytes

### ISSUE THREAD

**Issue by OzairKhanBro** [SpEcHiDe/UniBorg#17]
i am trying to deploy this app on heroku. I set the following environment variables
```
APP_ID
API_HASH
HU_STRING_SESSION
```
Then i tried to run application on heroku and i am facing following error.
`Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/app/.heroku/python/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/stdborg.py", line 42, in <module>
    StringSession(session_name),
  File "/app/.heroku/python/lib/python3.7/site-packages/telethon/sessions/string.py", line 38, in __init__
    _STRUCT_PREFORMAT.format(ip_len), StringSession.decode(string))
struct.error: unpack requires a buffer of 275 bytes`

and same error pops up on my local pc.

`Traceback (most recent call last):
  File "C:/Users/myname/PycharmProjects/bot/telesetup.py", line 15, in <module>
    client = TelegramClient(StringSession(api_session),
  File "C:\Users\myname\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telethon\sessions\string.py", line 38, in __init__
    _STRUCT_PREFORMAT.format(ip_len), StringSession.decode(string))
struct.error: unpack requires a buffer of 275 bytes`

anyone can help me what should i do?

**Comment by SpEcHiDe** [comment]
HU_STRING_SESSION variable is not defined properly. 

Please read the README.

**Comment by KingOfElephants** [comment]
Make sure you are filling valid values... 
Everything is properly Explained in  README.

**Comment by gajrajtherock** [comment]
@gajrajtherock

**Comment by KingOfElephants** [comment]
@gajrajtherock
