### ISSUE TITLE
Facing issues while uploading Folders

### ISSUE THREAD

**Issue by LucciferOO7** [SpEcHiDe/UniBorg#49]
INFO:oauth2client.client:Refreshing access_token
2020-02-21T06:43:50.692397+00:00 app[worker.1]: INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2020-02-21T06:43:50.833696+00:00 app[worker.1]: INFO:googleapiclient.discovery:URL being requested: POST https://www.googleapis.com/drive/v2/files?alt=json
2020-02-21T06:43:51.689404+00:00 app[worker.1]: INFO:googleapiclient.discovery:URL being requested: POST https://www.googleapis.com/drive/v2/files/1gITrE7arf9KLNSvD6V4rlcYvxkDS-jLY/permissions?alt=json
2020-02-21T06:43:52.570402+00:00 app[worker.1]: INFO:gDrive:Created Gdrive Folder:
2020-02-21T06:43:52.570414+00:00 app[worker.1]: Name: [Foxtrot] Vinland Saga - Volume 1 [BD 720p AAC]
2020-02-21T06:43:52.570415+00:00 app[worker.1]: ID: 1gITrE7arf9KLNSvD6V4rlcYvxkDS-jLY 
2020-02-21T06:43:52.570797+00:00 app[worker.1]: INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v2/rest
2020-02-21T06:43:52.717082+00:00 app[worker.1]: INFO:googleapiclient.discovery:URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable
2020-02-21T06:43:54.931733+00:00 app[worker.1]: ERROR:telethon.client.updates:Unhandled exception on _
2020-02-21T06:43:54.931743+00:00 app[worker.1]: Traceback (most recent call last):
2020-02-21T06:43:54.931744+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telethon/client/updates.py", line 428, in _dispatch_update
2020-02-21T06:43:54.931745+00:00 app[worker.1]:     await callback(event)
2020-02-21T06:43:54.931745+00:00 app[worker.1]:   File "stdplugins/gDrive.py", line 164, in _
2020-02-21T06:43:54.931745+00:00 app[worker.1]:     await DoTeskWithDir(http, input_str, mone, dir_id)
2020-02-21T06:43:54.931746+00:00 app[worker.1]:   File "stdplugins/gDrive.py", line 365, in DoTeskWithDir
2020-02-21T06:43:54.931747+00:00 app[worker.1]:     g_drive_link = await upload_file(http, current_file_name, file_name, mime_type, event, parent_id)
2020-02-21T06:43:54.931747+00:00 app[worker.1]:   File "stdplugins/gDrive.py", line 299, in upload_file
2020-02-21T06:43:54.931747+00:00 app[worker.1]:     status, response = file.next_chunk()
2020-02-21T06:43:54.931748+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
2020-02-21T06:43:54.931748+00:00 app[worker.1]:     return wrapped(*args, **kwargs)
2020-02-21T06:43:54.931749+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/googleapiclient/http.py", line 988, in next_chunk
2020-02-21T06:43:54.931749+00:00 app[worker.1]:     headers=headers)
2020-02-21T06:43:54.931749+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/oauth2client/transport.py", line 175, in new_request
2020-02-21T06:43:54.931750+00:00 app[worker.1]:     redirections, connection_type)
2020-02-21T06:43:54.931750+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/oauth2client/transport.py", line 282, in request
2020-02-21T06:43:54.931751+00:00 app[worker.1]:     connection_type=connection_type)
2020-02-21T06:43:54.931751+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/httplib2/__init__.py", line 1991, in request
2020-02-21T06:43:54.931752+00:00 app[worker.1]:     cachekey,
2020-02-21T06:43:54.931753+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/httplib2/__init__.py", line 1690, in _request
2020-02-21T06:43:54.931753+00:00 app[worker.1]:     content,
2020-02-21T06:43:54.931754+00:00 app[worker.1]: httplib2.RedirectMissingLocation: Redirected but the response is missing a Location: header.

**Comment by SpEcHiDe** [comment]
The httplib requirement needs to be as per: https://stackoverflow.com/a/59826168/4723940 till the gDrive can fix the [issue](https://github.com/googleapis/google-api-python-client/issues/803)
