### ISSUE TITLE
Error with python3 -m stdborg SESSION

### ISSUE THREAD

**Issue by buzz3rs** [SpEcHiDe/UniBorg#96]
Hello, 
i was trying the install instructions but i always come to this error :
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/montather/stdborg.py", line 9, in <module>
    from uniborg import Uniborg
  File "/root/montather/uniborg/__init__.py", line 5, in <module>
    from .uniborg import *
  File "/root/montather/uniborg/uniborg.py", line 60
    for a_plugin_path in Path().glob(f"{self.n_plugin_path}/*.py"):
                                                                ^
SyntaxError: invalid syntax
```

i have python 3.5
Im not very good with python so there might be something wrong im doing ?

**Comment by SpEcHiDe** [comment]
please update to atleast python 3.5.3.
